title: Luka Finžgar's Blog
description: Mobile Development Expert with 15 years of experience in iOS and Android development
baseurl: ""
url: "https://lukafinzgar.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 