name: Generate Podcasts

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  generate-podcasts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install podcastfy pyyaml python-dotenv
    
    - name: Generate podcasts
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python generate_podcast.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Generate podcasts" || echo "No changes to commit"
        git push 